### ISSUE TITLE
Investigate issue with config format not working for LuckPerms rangs.

### ISSUE THREAD

**Issue by CitralFlo** [EternalCodeTeam/ChatFormatter#124]
Problem:
ChatFormatter placeholders with Papi placeholders do not display actual data.
ChatFormatter does not use custom format settings for LuckPerms rangs even doe they share the same name.
There are no istructions to usage of `format: ` settings.

Repro steps:
1. Setup server, with Vault, PlaceholderAPI, LuckPerms and Chatforatter.
2. Setup PlaceholderAPI expansion for LuckPerms.
3. Update Chatformatter config with custom formating for LuckPerms groups ex.
```yml
defaultFormat: "{displayname} {arrow_right} {message}"
format:
  default: "{member} &f{displayname} &8{arrow_right} {message} "
  vip: "{prefix} &b{displayname} &8{arrow_right} {message} "
  admin: "$template({admin}, &c)"

# It is used to shorten the text even more and keep the clean file!
templates:
  - "$template($rank, $color) -> '$rank $color{displayname} &8{arrow_right} $color{message}'"

# Placeholders, it allows you to make a shorter text, you can use some prefixes, characters etc. 
placeholders:
  {displayname}: "<displayname>"
  {name}: "<name>"
  {message}: "<message>"
  {prefix}: "<b>%luckperms_prefix%</b>"
```
4. Setup LuckPerms group ex.
![image](https://github.com/EternalCodeTeam/ChatFormatter/assets/80779749/cb1a38c8-7b36-4d67-89ab-35e7bbff0fb2)
and save changes.
5. Reload all configs

Outcome:
Custom rank format does not work. Player is given defaultFormat, even when his parent group is setup to the same name as format. Additionaly, using `{prefix}` inside: defaultFormat displays:
![image](https://github.com/EternalCodeTeam/ChatFormatter/assets/80779749/efedef44-9d21-41c7-a376-59c70d8d007f)

Temporary solution:
User raw placeholderApi placeholders inside defaultFormat. Like:
`defaultFormat: "%luckperms_prefix% {displayname} {arrow_right} {message}"`

Sugestions:
> Make config more user friendly by matching format for groups with LP group names.
> Update instructions to match game logic.
